# @Author: Haibin Lee <haibin>
# @Date:   2021-03-12T16:08:43+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: download.yml
# @Last modified by:   haibin
# @Last modified time: 2021-03-12T16:11:40+08:00
# @Copyright: Copyright 2020 the original author or authors.

- name: 下载解压安装文件
  unarchive:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ wecross_workdir }}/"
  loop: "{{ wecross_dl_url }}"
